FROM golang:bullseye

RUN apt-get update && apt-get install -y tzdata

RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /app

COPY . /app

RUN go mod download

ENTRYPOINT ["/go/bin/CompileDaemon", "-polling", "-verbose", "-exclude-dir=.git", "-exclude-dir=.vscode", "-exclude-dir=.idea", "-exclude-dir=logs", "-exclude-dir=storage", "--build=/usr/local/go/bin/go build main.go", "--command=./main"]