services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - storage:/app/storage
    networks:
      - template-network

volumes:
  storage:

networks:
  template-network:
    driver:
      bridge