// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   pgtype.UUID
	Name string
	Bio  pgtype.Text
}
